name: expense_tracker_app
description: "A Flutter expense tracker application."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.18+61

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  get: ^4.6.6               # State management and navigation
  get_storage: ^2.1.1       # Local storage solution
  shared_preferences: ^2.5.1 # Required for PIN service
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  flutter_dynamic_icon: ^2.1.0
  device_preview: ^1.2.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  firebase_auth: ^5.5.4

  # Networking
  dio: ^5.8.0+1             # HTTP client
  connectivity_plus: ^6.1.2 # Network connectivity

  # Utilities
  intl: ^0.19.0             # Internationalization and formatting
  dartz: ^0.10.1            # Functional programming features
  device_info_plus: ^11.3.3 # Device information
  pretty_dio_logger: ^1.4.0
  local_auth: ^2.3.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  animations: ^2.0.11

  # UI components
  flutter_svg: ^2.0.17      # SVG rendering
  toastification: ^2.1.0    # Toast messages
  skeletonizer: ^1.4.3      # Loading skeletons
  cached_network_image: ^3.4.1 # Image caching
  percent_indicator: ^4.2.4  # Progress indicators
  flutter_easy_dialogs: ^4.0.3 # Dialogs
  awesome_dialog: ^3.2.1    # Advanced dialogs


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # App icon generation

  # For models and code generation (if you're using them)
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/brand/
    - assets/sounds/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Oswald
      fonts:
        - asset: assets/fonts/oswald/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/oswald/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/oswald/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/oswald/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/oswald/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/oswald/Oswald-SemiBold.ttf
          weight: 600
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/source_code_pro/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/source_code_pro/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_code_pro/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/source_code_pro/SourceCodePro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/source_code_pro/SourceCodePro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Italic.ttf
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_code_pro/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/source_code_pro/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/source_code_pro/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_code_pro/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_code_pro/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/brand/logo-transparent.png"
  adaptive_icon_background: "#5E72E4"  # Your primary color
  adaptive_icon_foreground: "assets/brand/logo-transparent.png"